Repository MannLabs/alphabase, pull requests merged in 2025-08, with the labels that each got.

#336 Making adding new SMILES easier & adding new PTMs
  alphabase/constants/const_files/modification.tsv
  alphabase/smiles/adding_smiles.py
  alphabase/smiles/peptide.py
  docs/nbs/adding_smiles.ipynb
  docs/notebooks.rst
  docs/tutorials/adding_smiles.rst
  tests/test_peptide_smiles.py
Labels: code-review

#331 Spectronaut PG Reader
  alphabase/constants/const_files/pg_reader.yaml
  alphabase/pg_reader/__init__.py
  alphabase/pg_reader/alphapept_pg_reader.py
  alphabase/pg_reader/fragpipe_pg_reader.py
  alphabase/pg_reader/maxquant_pg_reader.py
  alphabase/pg_reader/mztab_pg_reader.py
  alphabase/pg_reader/pg_reader.py
  alphabase/pg_reader/spectronaut_reader.py
  docs/api.rst
  docs/modules_pg_reader.rst
  docs/pg_reader/alphadia_pg_reader.rst
  docs/pg_reader/alphapept_pg_reader.rst
  docs/pg_reader/diann_pg_reader.rst
  docs/pg_reader/fragpipe_pg_reader.rst
  docs/pg_reader/maxquant_pg_reader.rst
  docs/pg_reader/mztab_pg_reader.rst
  docs/pg_reader/pg_base.rst
  docs/pg_reader/spectronaut_pg_reader.rst
  tests/integration/conftest.py
  tests/integration/reference_data/reference_pg_fragpipe.parquet
  tests/integration/reference_data/reference_pg_mztab_minimal.parquet
  tests/integration/reference_data/reference_pg_spectronaut_18.0.tsv.parquet
  tests/integration/test_pg_reader_provider.py
  tests/integration/test_pg_readers.py
Labels: enhancement

#330 MaxQuant ProteinGroup Reader
  alphabase/constants/const_files/pg_reader.yaml
  alphabase/pg_reader/__init__.py
  alphabase/pg_reader/alphapept_pg_reader.py
  alphabase/pg_reader/fragpipe_pg_reader.py
  alphabase/pg_reader/maxquant_pg_reader.py
  alphabase/pg_reader/mztab_pg_reader.py
  alphabase/pg_reader/pg_reader.py
  alphabase/pg_reader/spectronaut_reader.py
  docs/api.rst
  docs/modules_pg_reader.rst
  docs/pg_reader/alphadia_pg_reader.rst
  docs/pg_reader/alphapept_pg_reader.rst
  docs/pg_reader/diann_pg_reader.rst
  docs/pg_reader/fragpipe_pg_reader.rst
  docs/pg_reader/maxquant_pg_reader.rst
  docs/pg_reader/mztab_pg_reader.rst
  docs/pg_reader/pg_base.rst
  docs/pg_reader/spectronaut_pg_reader.rst
  tests/integration/conftest.py
  tests/integration/reference_data/reference_pg_fragpipe.parquet
  tests/integration/reference_data/reference_pg_maxquant.2024.tsv.parquet
  tests/integration/reference_data/reference_pg_mztab_minimal.parquet
  tests/integration/reference_data/reference_pg_spectronaut_18.0.tsv.parquet
  tests/integration/test_pg_reader_provider.py
  tests/integration/test_pg_readers.py
Labels: enhancement

#327 AlphaPept Protein Group Reader
  alphabase/constants/const_files/pg_reader.yaml
  alphabase/pg_reader/__init__.py
  alphabase/pg_reader/alphapept_pg_reader.py
  alphabase/pg_reader/fragpipe_pg_reader.py
  alphabase/pg_reader/keys.py
  alphabase/pg_reader/maxquant_pg_reader.py
  alphabase/pg_reader/mztab_pg_reader.py
  alphabase/pg_reader/pg_reader.py
  alphabase/pg_reader/spectronaut_reader.py
  docs/api.rst
  docs/modules_pg_reader.rst
  docs/pg_reader/alphadia_pg_reader.rst
  docs/pg_reader/alphapept_pg_reader.rst
  docs/pg_reader/diann_pg_reader.rst
  docs/pg_reader/fragpipe_pg_reader.rst
  docs/pg_reader/maxquant_pg_reader.rst
  docs/pg_reader/mztab_pg_reader.rst
  docs/pg_reader/pg_base.rst
  docs/pg_reader/spectronaut_pg_reader.rst
  requirements/requirements.txt
  requirements/requirements_loose.txt
  tests/integration/conftest.py
  tests/integration/reference_data/reference_pg_alphadia_1.10.0.tsv.parquet
  tests/integration/reference_data/reference_pg_alphapept_0.5.3.tsv.parquet
  tests/integration/reference_data/reference_pg_diann_1.8.1.tsv.parquet
  tests/integration/reference_data/reference_pg_fragpipe.parquet
  tests/integration/reference_data/reference_pg_maxquant.2024.tsv.parquet
  tests/integration/reference_data/reference_pg_mztab_minimal.parquet
  tests/integration/reference_data/reference_pg_spectronaut_18.0.tsv.parquet
  tests/integration/test_pg_reader_provider.py
  tests/integration/test_pg_readers.py
  tests/unit/pg_reader/test_alphapept_pg_reader.py
  tests/unit/pg_reader/test_pg_reader.py
  tests/unit/pg_reader/test_pg_reader_provider.py
Labels: enhancement

#325 DIANN Protein Group Reader
  alphabase/constants/const_files/pg_reader.yaml
  alphabase/pg_reader/__init__.py
  alphabase/pg_reader/alphapept_pg_reader.py
  alphabase/pg_reader/diann_pg_reader.py
  alphabase/pg_reader/fragpipe_pg_reader.py
  alphabase/pg_reader/keys.py
  alphabase/pg_reader/maxquant_pg_reader.py
  alphabase/pg_reader/mztab_pg_reader.py
  alphabase/pg_reader/pg_reader.py
  alphabase/pg_reader/spectronaut_reader.py
  docs/api.rst
  docs/modules_pg_reader.rst
  docs/pg_reader/alphadia_pg_reader.rst
  docs/pg_reader/alphapept_pg_reader.rst
  docs/pg_reader/diann_pg_reader.rst
  docs/pg_reader/fragpipe_pg_reader.rst
  docs/pg_reader/maxquant_pg_reader.rst
  docs/pg_reader/mztab_pg_reader.rst
  docs/pg_reader/pg_base.rst
  docs/pg_reader/spectronaut_pg_reader.rst
  requirements/requirements.txt
  requirements/requirements_loose.txt
  tests/integration/conftest.py
  tests/integration/reference_data/reference_pg_alphadia_1.10.0.tsv.parquet
  tests/integration/reference_data/reference_pg_alphapept_0.5.3.tsv.parquet
  tests/integration/reference_data/reference_pg_diann_1.8.1.tsv.parquet
  tests/integration/reference_data/reference_pg_fragpipe.parquet
  tests/integration/reference_data/reference_pg_maxquant.2024.tsv.parquet
  tests/integration/reference_data/reference_pg_mztab_minimal.parquet
  tests/integration/reference_data/reference_pg_spectronaut_18.0.tsv.parquet
  tests/integration/test_pg_reader_provider.py
  tests/integration/test_pg_readers.py
  tests/unit/pg_reader/test_alphapept_pg_reader.py
  tests/unit/pg_reader/test_pg_reader.py
  tests/unit/pg_reader/test_pg_reader_provider.py
Labels: enhancement

#338 [Fix] Hotfix alphabase hdf5
  .github/workflows/pip_installation.yml
  README.md
  misc/pip_install.sh
Labels: bug

#340 Remove pytables as a dependency
  .github/workflows/pip_installation.yml
  README.md
  alphabase/pg_reader/alphapept_pg_reader.py
  misc/pip_install.sh
  pyproject.toml
  requirements/requirements.txt
  requirements/requirements_hdf_loose.txt
  requirements/requirements_loose.txt
  tests/integration/conftest.py
  tests/integration/test_pg_readers.py
Labels: bug

#323 Tutorial on `scverse` compatibility
  docs/tutorials/tutorial_scverse_compatibility.ipynb
  requirements/requirements_docs.txt
  requirements/requirements_tests.txt
Labels: documentation

#335 PG Reader - Tutorial
  docs/notebooks.rst
  docs/tutorials/tutorial_pg_reader.ipynb
Labels: documentation
